#encoding: utf-8

if File.symlink?(__FILE__)
  root_dir = File::dirname(File::expand_path(File::readlink(__FILE__)))
else
  root_dir = File::dirname(File::expand_path(__FILE__))
end

Dir::glob("#{root_dir}/lib/*.rb").each do |file|
  require file
end

Dir::glob("#{root_dir}/conf/*.rake").each do |file|
  load file
end

desc 'for test'
task :test do
  "hogehoge"
end


